export class SolicitudFinanciamientoModel {
    public idCliente?: number;
    public nombres?: string;
    public apellidos?: string;
    public numeroDocumento?: string;
    public codUbigeo?: string;
    public fechaEmision?: Date;
    public fechaNacimiento?: Date;
    public estadoCivil?: number;
    public correoElectronico?: string;
    public celular?: string;
    public idNivelEstudios?: number;
    public ocupacion?: string;
    public tipoContrato?: string;
    public tiempoEmpleoCliente?: string;
    public tipoCalle?: string;
    public direccion?: string;
    public numeroInterior?: number;
    public mzLt?: string;
    public distrito?: string;
    public referenciaDomicilio?: string;
    public tipoVivienda?: string;
    public tiempoAnoVivienda?: number;
    public tiempoMesesVivienda?: number;
    public isGasNatural?: boolean;
    public numeroPlaca?: string;
    public marcaAuto?: string;
    public modeloAuto?: string;
    public fechaFabricacion?: Date;
    public numeroTarjetaPropiedad?: string;
    public tipoCilindroMotor?: string;
    public tipoUsoVehicular?: boolean;
    public estadoVehiculo?: number;
    public ingresoMensual?: string;
    public numeroHijos?: number;
    public nombreEstablecimiento?: string;
    public tipoFinanciamiento?: string;
    public tipoCredito?: number;
    public plazoCuotasFinanciamiento?: string;
    public montoFinanciamiento?: number;
    public observaciones?: string;
    public idTaller?: number;
    public numeroScore?:number;
    public idPreevaluacion?:number;
    public flagContratoFinanciamiento?:boolean;
    public flagFormatoConformidad?:boolean;
    public flagDNI?:boolean;
    public digitoVerificadorDNI?:string;
    //public tconformidad?:boolean;
    public FlagpoliticasCondiciones?:boolean;
    public MesAnio?:string;
    public mesAnio?:string;
    public idSfCliente?:number;
    public idSfClientetemp?:number;
    //public checkDNI?:boolean;
    //public checkContrFinanciamiento?:boolean;

}